name: frontend-ci

on: 
  push:
    branches: 
      - develop
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: dependcices
        run: npm install

      - name: build as package
        run: npm run build

      - name: test
        run: npm test

