name: First-workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-24.04

    steps:
      - name: greetings
        run: echo "Hi, Hello world"

      - name: exit
        run: echo "Good, Bye"
